// rdma_pingpong.c
// Event-driven RDMA RC ping-pong using rdma_cm + ibverbs completion channel.
// Server: ./rdma_pingpong -s -p 7471 -n 1000
// Client: ./rdma_pingpong -a <server_ip> -p 7471 -n 1000

// TODO: This code is purely generated by ChatGPT, and we still need the check the perftest code. Actually we won't need this shit if perftest can be migrated.

#define _POSIX_C_SOURCE 200809L
#include <arpa/inet.h>
#include <errno.h>
#include <inttypes.h>
#include <netdb.h>
#include <rdma/rdma_cma.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/time.h>
#include <time.h>
#include <unistd.h>

#define MSG_SIZE      64
#define CQ_DEPTH      16
#define MAX_SGE       1
#define MAX_WR        16

static void die(const char *msg) {
    perror(msg);
    exit(EXIT_FAILURE);
}

struct pp_ctx {
    // CM / QP
    struct rdma_event_channel *cm_chan;
    struct rdma_cm_id *id;          // active (client) or passive (server accepted) id
    struct ibv_pd *pd;
    struct ibv_comp_channel *comp_chan;
    struct ibv_cq *cq;
    struct ibv_qp *qp;

    // MR / buffers
    void *buf;
    struct ibv_mr *mr;

    // SGE / WR templates
    struct ibv_sge sge;
    struct ibv_send_wr swr;
    struct ibv_recv_wr rwr;

    // bookkeeping
    int iters;
    int sends;
    int recvs;
    bool is_server;
};

static void fill_msg(void *buf, const char *text, int seq) {
    char tmp[MSG_SIZE];
    snprintf(tmp, sizeof(tmp), "%s #%d", text, seq);
    memset(buf, 0, MSG_SIZE);
    memcpy(buf, tmp, strnlen(tmp, MSG_SIZE));
}

static void cq_arm(struct pp_ctx *ctx) {
    if (ibv_req_notify_cq(ctx->cq, 0))
        die("ibv_req_notify_cq");
}

static void post_one_recv(struct pp_ctx *ctx) {
    memset(&ctx->sge, 0, sizeof(ctx->sge));
    ctx->sge.addr   = (uintptr_t)ctx->buf;
    ctx->sge.length = MSG_SIZE;
    ctx->sge.lkey   = ctx->mr->lkey;

    memset(&ctx->rwr, 0, sizeof(ctx->rwr));
    ctx->rwr.sg_list = &ctx->sge;
    ctx->rwr.num_sge = 1;

    struct ibv_recv_wr *bad = NULL;
    if (ibv_post_recv(ctx->qp, &ctx->rwr, &bad))
        die("ibv_post_recv");
}

static void post_one_send(struct pp_ctx *ctx, const char *tag) {
    fill_msg(ctx->buf, tag, ctx->sends);

    memset(&ctx->sge, 0, sizeof(ctx->sge));
    ctx->sge.addr   = (uintptr_t)ctx->buf;
    ctx->sge.length = MSG_SIZE;
    ctx->sge.lkey   = ctx->mr->lkey;

    memset(&ctx->swr, 0, sizeof(ctx->swr));
    ctx->swr.opcode    = IBV_WR_SEND;
    ctx->swr.send_flags = IBV_SEND_SIGNALED;
    ctx->swr.sg_list   = &ctx->sge;
    ctx->swr.num_sge   = 1;

    struct ibv_send_wr *bad = NULL;
    if (ibv_post_send(ctx->qp, &ctx->swr, &bad))
        die("ibv_post_send");
}

static void create_qp_stack(struct pp_ctx *ctx) {
    ctx->pd = ibv_alloc_pd(ctx->id->verbs);
    if (!ctx->pd) die("ibv_alloc_pd");

    ctx->comp_chan = ibv_create_comp_channel(ctx->id->verbs);
    if (!ctx->comp_chan) die("ibv_create_comp_channel");

    ctx->cq = ibv_create_cq(ctx->id->verbs, CQ_DEPTH, NULL, ctx->comp_chan, 0);
    if (!ctx->cq) die("ibv_create_cq");

    cq_arm(ctx);

    struct ibv_qp_init_attr qattr = {
        .send_cq = ctx->cq,
        .recv_cq = ctx->cq,
        .qp_type = IBV_QPT_RC,
        .cap = {
            .max_send_wr  = MAX_WR,
            .max_recv_wr  = MAX_WR,
            .max_send_sge = MAX_SGE,
            .max_recv_sge = MAX_SGE,
        },
    };

    if (rdma_create_qp(ctx->id, ctx->pd, &qattr))
        die("rdma_create_qp");
    ctx->qp = ctx->id->qp;

    // Register a single message buffer for both send and recv.
    if (posix_memalign(&ctx->buf, sysconf(_SC_PAGESIZE), MSG_SIZE))
        die("posix_memalign");
    memset(ctx->buf, 0, MSG_SIZE);

    ctx->mr = ibv_reg_mr(ctx->pd, ctx->buf, MSG_SIZE,
                         IBV_ACCESS_LOCAL_WRITE);
    if (!ctx->mr) die("ibv_reg_mr");
}

static void destroy_qp_stack(struct pp_ctx *ctx) {
    if (ctx->qp) rdma_destroy_qp(ctx->id);
    if (ctx->cq) ibv_destroy_cq(ctx->cq);
    if (ctx->comp_chan) ibv_destroy_comp_channel(ctx->comp_chan);
    if (ctx->mr) ibv_dereg_mr(ctx->mr);
    if (ctx->buf) free(ctx->buf);
    if (ctx->pd) ibv_dealloc_pd(ctx->pd);
}

static void run_completion_loop(struct pp_ctx *ctx) {
    // Each side keeps one RECV posted at a time.
    post_one_recv(ctx);

    // Client kicks off ping; server waits for RECV first.
    if (!ctx->is_server) {
        post_one_send(ctx, "ping");
        ctx->sends++;
    }

    while (ctx->recvs < ctx->iters || ctx->sends < ctx->iters) {
        struct ibv_cq *ev_cq = NULL;
        void *ev_ctx = NULL;
        if (ibv_get_cq_event(ctx->comp_chan, &ev_cq, &ev_ctx))
            die("ibv_get_cq_event");
        ibv_ack_cq_events(ev_cq, 1);
        cq_arm(ctx);

        struct ibv_wc wc;
        int n;
        while ((n = ibv_poll_cq(ctx->cq, 1, &wc)) > 0) {
            if (wc.status != IBV_WC_SUCCESS) {
                fprintf(stderr, "WC error status %d (%s) opcode %d\n",
                        wc.status, ibv_wc_status_str(wc.status), wc.opcode);
                exit(EXIT_FAILURE);
            }

            switch (wc.opcode) {
            case IBV_WC_RECV:
                ctx->recvs++;
                // Immediately repost a RECV for next round (single in-flight RECV).
                post_one_recv(ctx);

                if (ctx->is_server) {
                    // On server: reply with a pong on each recv until iters reached.
                    if (ctx->sends < ctx->iters) {
                        post_one_send(ctx, "pong");
                        ctx->sends++;
                    }
                } else {
                    // On client: after receiving pong (or any recv), if more rounds, send next ping.
                    if (ctx->sends < ctx->iters) {
                        post_one_send(ctx, "ping");
                        ctx->sends++;
                    }
                }
                break;

            case IBV_WC_SEND:
                // Nothing to do besides accounting if you like.
                break;

            default:
                // We only expect SEND and RECV completions here.
                break;
            }
        }
        if (n < 0) die("ibv_poll_cq");
    }
}

static void client_flow(const char *server_addr, const char *port, int iters) {
    struct pp_ctx ctx = {.iters = iters, .is_server = false};

    ctx.cm_chan = rdma_create_event_channel();
    if (!ctx.cm_chan) die("rdma_create_event_channel");

    if (rdma_create_id(ctx.cm_chan, &ctx.id, NULL, RDMA_PS_TCP))
        die("rdma_create_id");

    struct addrinfo hints = {0}, *res = NULL;
    hints.ai_family   = AF_UNSPEC;
    hints.ai_socktype = SOCK_STREAM;

    if (getaddrinfo(server_addr, port, &hints, &res))
        die("getaddrinfo");

    if (rdma_resolve_addr(ctx.id, NULL, res->ai_addr, 2000))
        die("rdma_resolve_addr");
    freeaddrinfo(res);

    struct rdma_cm_event *ev;
    if (rdma_get_cm_event(ctx.cm_chan, &ev)) die("rdma_get_cm_event");
    if (ev->event != RDMA_CM_EVENT_ADDR_RESOLVED) die("ADDR_RESOLVED");
    rdma_ack_cm_event(ev);

    if (rdma_resolve_route(ctx.id, 2000))
        die("rdma_resolve_route");
    if (rdma_get_cm_event(ctx.cm_chan, &ev)) die("rdma_get_cm_event");
    if (ev->event != RDMA_CM_EVENT_ROUTE_RESOLVED) die("ROUTE_RESOLVED");
    rdma_ack_cm_event(ev);

    create_qp_stack(&ctx);

    struct rdma_conn_param cp = {0};
    cp.initiator_depth = 1;
    cp.responder_resources = 1;
    cp.rnr_retry_count = 7; // infinite retry

    if (rdma_connect(ctx.id, &cp))
        die("rdma_connect");

    if (rdma_get_cm_event(ctx.cm_chan, &ev)) die("rdma_get_cm_event");
    if (ev->event != RDMA_CM_EVENT_ESTABLISHED) die("ESTABLISHED");
    rdma_ack_cm_event(ev);

    run_completion_loop(&ctx);

    rdma_disconnect(ctx.id);
    if (rdma_get_cm_event(ctx.cm_chan, &ev)) die("rdma_get_cm_event");
    if (ev->event != RDMA_CM_EVENT_DISCONNECTED) die("DISCONNECTED");
    rdma_ack_cm_event(ev);

    printf("[client] sends=%d recvs=%d\n", ctx.sends, ctx.recvs);

    destroy_qp_stack(&ctx);
    rdma_destroy_id(ctx.id);
    rdma_destroy_event_channel(ctx.cm_chan);
}

static void server_flow(const char *port, int iters) {
    struct pp_ctx lctx = {0}; // listener context
    lctx.is_server = true;
    lctx.iters = iters;

    lctx.cm_chan = rdma_create_event_channel();
    if (!lctx.cm_chan) die("rdma_create_event_channel");

    if (rdma_create_id(lctx.cm_chan, &lctx.id, NULL, RDMA_PS_TCP))
        die("rdma_create_id");

    struct addrinfo hints = {0}, *res = NULL;
    hints.ai_flags = AI_PASSIVE;
    hints.ai_family = AF_UNSPEC;
    hints.ai_socktype = SOCK_STREAM;

    if (getaddrinfo(NULL, port, &hints, &res))
        die("getaddrinfo");

    if (rdma_bind_addr(lctx.id, res->ai_addr))
        die("rdma_bind_addr");
    freeaddrinfo(res);

    if (rdma_listen(lctx.id, 1))
        die("rdma_listen");

    // Wait for a connection request.
    struct rdma_cm_event *ev;
    if (rdma_get_cm_event(lctx.cm_chan, &ev)) die("rdma_get_cm_event");
    if (ev->event != RDMA_CM_EVENT_CONNECT_REQUEST) die("CONNECT_REQUEST");

    // Create a per-connection context (ctx) on the child id
    struct pp_ctx ctx = {.iters = iters, .is_server = true};
    ctx.cm_chan = lctx.cm_chan;
    ctx.id = ev->id; // child id for this connection

    create_qp_stack(&ctx);

    struct rdma_conn_param cp = {0};
    cp.initiator_depth = 1;
    cp.responder_resources = 1;
    cp.rnr_retry_count = 7;

    if (rdma_accept(ctx.id, &cp))
        die("rdma_accept");
    rdma_ack_cm_event(ev);

    if (rdma_get_cm_event(ctx.cm_chan, &ev)) die("rdma_get_cm_event");
    if (ev->event != RDMA_CM_EVENT_ESTABLISHED) die("ESTABLISHED");
    rdma_ack_cm_event(ev);

    run_completion_loop(&ctx);

    // Disconnect and cleanup child.
    if (rdma_disconnect(ctx.id))
        die("rdma_disconnect");
    if (rdma_get_cm_event(ctx.cm_chan, &ev)) die("rdma_get_cm_event");
    if (ev->event != RDMA_CM_EVENT_DISCONNECTED) die("DISCONNECTED");
    rdma_ack_cm_event(ev);

    printf("[server] sends=%d recvs=%d\n", ctx.sends, ctx.recvs);

    destroy_qp_stack(&ctx);

    // Destroy listener (parent) id & channel.
    rdma_destroy_id(lctx.id);
    rdma_destroy_event_channel(lctx.cm_chan);
}

static void usage(const char *prog) {
    fprintf(stderr,
        "Usage:\n"
        "  Server: %s -s -p <port> [-n <iters>]\n"
        "  Client: %s -a <addr> -p <port> [-n <iters>]\n",
        prog, prog);
}

int main(int argc, char **argv) {
    const char *addr = NULL;
    const char *port = "7471";
    int iters = 1;
    bool is_server = false;

    int opt;
    while ((opt = getopt(argc, argv, "sa:p:n:")) != -1) {
        switch (opt) {
        case 's': is_server = true; break;
        case 'a': addr = optarg; break;
        case 'p': port = optarg; break;
        case 'n': iters = atoi(optarg); break;
        default: usage(argv[0]); return EXIT_FAILURE;
        }
    }
    if (iters <= 0) iters = 1;

    if (is_server) {
        server_flow(port, iters);
    } else {
        if (!addr) { usage(argv[0]); return EXIT_FAILURE; }
        client_flow(addr, port, iters);
    }
    return 0;
}
